### PR TITLE
Added entries to allow notes column

### LINKED ISSUE #34: Notes column for curation records
Allow a column for curators to make notes in records.

notes:
  description: "Column for curator notes (notes will not be checked or loaded)."
  compulsory: False
  yaml: False

Add above entry to 'common_fields_spec.yaml' file in new_metadata/ and new_images/
There is no 'common_fields_spec.yaml' in new_datasets/ - add to ds_spec.yaml

### PR DESCRIPTION
**Pull request by Clare72**
fixes #34

### CODE REVIEW

**Comment by dosumis** [comment]
Could you also edited the test files to check this has worked.  

Adding a notes  column to newmeta_Jovanovic2016_191106.tsv in  https://github.com/VirtualFlyBrain/curation/tree/master/src/vfb/curation/test/resources/records/new_metadata/working

should be sufficient.   If your edits to  config have worked, travis tests should pass.

As long as that works, I'm happy for you to merge pull

**Review by dosumis — CHANGES_REQUESTED** [review]
Changes to conf files  look good 

Could you also edit test files to check this has worked?

Adding a notes column to newmeta_Jovanovic2016_191106.tsv in https://github.com/VirtualFlyBrain/curation/tree/master/src/vfb/curation/test/resources/records/new_metadata/working

should be sufficient. If your edits to config have worked, travis tests should pass.

As long as that works, I'm happy for you to merge pull

**Comment by dosumis** [comment]
Looks like failures due to some problem with KB container running on Travis.  Nothing to to with your edits, which look  good  to me.   @Robbie1977   - any ideas?

**Comment by Robbie1977** [comment]
@Clare72 fixed although nothing has changed, however, if it occurs again we can see why.

**Review by dosumis — APPROVED** [review]

**Pull request merged**
